// <auto-generated />
using System;
using KuaforYonetim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuaforYonetim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241125200941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuaforYonetim.Modelss.Calisan", b =>
                {
                    b.Property<int?>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CalisanId"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SalonId")
                        .HasColumnType("int");

                    b.Property<string>("Uzmanlik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalisanId");

                    b.HasIndex("SalonId");

                    b.ToTable("Calisanlar");

                    b.HasData(
                        new
                        {
                            CalisanId = 1,
                            AdSoyad = "Ayşe Yılmaz",
                            Uzmanlik = "Saç Kesimi"
                        },
                        new
                        {
                            CalisanId = 2,
                            AdSoyad = "Mehmet Can",
                            Uzmanlik = "Boyama"
                        },
                        new
                        {
                            CalisanId = 3,
                            AdSoyad = "Elif Demir",
                            Uzmanlik = "Manikür"
                        });
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Hizmet", b =>
                {
                    b.Property<int?>("HizmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("HizmetId"));

                    b.Property<string>("HizmetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalonId")
                        .HasColumnType("int");

                    b.Property<double>("Sure")
                        .HasColumnType("float");

                    b.Property<decimal>("Ucret")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("HizmetId");

                    b.HasIndex("SalonId");

                    b.ToTable("Hizmetler");

                    b.HasData(
                        new
                        {
                            HizmetId = 1,
                            HizmetAdi = "Kısa Saç Kesimi",
                            Sure = 30.0,
                            Ucret = 100m
                        },
                        new
                        {
                            HizmetId = 2,
                            HizmetAdi = "Saç Boyama",
                            Sure = 90.0,
                            Ucret = 200m
                        },
                        new
                        {
                            HizmetId = 3,
                            HizmetAdi = "Manikür",
                            Sure = 45.0,
                            Ucret = 150m
                        });
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"));

                    b.Property<DateTime?>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int?>("HizmetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ucret")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("RandevuId");

                    b.HasIndex("CalisanId");

                    b.HasIndex("HizmetId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Salon", b =>
                {
                    b.Property<int?>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SalonId"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalonId");

                    b.ToTable("Salon");
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Calisan", b =>
                {
                    b.HasOne("KuaforYonetim.Modelss.Salon", "Salon")
                        .WithMany("Calisanlar")
                        .HasForeignKey("SalonId");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Hizmet", b =>
                {
                    b.HasOne("KuaforYonetim.Modelss.Salon", "Salon")
                        .WithMany("Hizmetler")
                        .HasForeignKey("SalonId");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Randevu", b =>
                {
                    b.HasOne("KuaforYonetim.Modelss.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId");

                    b.HasOne("KuaforYonetim.Modelss.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId");

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("KuaforYonetim.Modelss.Salon", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Hizmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
